Clean-up eslint config
This now includes all applicable folders in eslint processing. Resolved all
issues that came out of eslint now running on all applicable sources.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -60,27 +60,71 @@ jobs:
     steps:
       - name: Checkout
         uses: Brightspace/third-party-actions@actions/checkout
+      - name: Set up node
+        uses: Brightspace/third-party-actions@actions/setup-node
+        with:
+          node-version: ${{env.NODE_VERSION}}
+      - name: Set up cache
+        uses: Brightspace/third-party-actions@actions/cache
+        id: cache
+        with:
+          path: '**/node_modules'
+          key: npm-${{ hashFiles('**/package-lock.json') }}
+      - name: Install dependencies
+        if: steps.cache.outputs.cache-hit != 'true'
+        run: npm ci
       - name: Verify Languages
         run: |
-          status=0
-          for lang in ./serge/*.json
-          do
-            tmpLang="$(basename $lang)"
-            echo "Verifying: $tmpLang"
-            tmpLang="./lang/${tmpLang/json/js.expected}"
-            printf "export default " | cat -s - "$lang" > "$tmpLang"
-            sed -i 's/\}\s*$/\};/' "$tmpLang"
-            diff -b -B "${tmpLang%.expected}" "$tmpLang"
-            if [ $? -ne 0 ]; then
-              echo "Failed: $tmpLang"
-              status=1
-            fi
-            rm "$tmpLang"
+          match=true
+          target_files=$(ls -1 lang/ | sed -e 's/\.js$//')
+          source_files=$(ls -1 serge/ | sed -e 's/\.json$//')
+          all_files=$(echo -e "$target_files\n$source_files" | sort | uniq)
+          missing_sources=()
+          missing_targets=()
+          echo 'Checking file sets match'
+          for file in $all_files; do
+              source="serge/$file.json"
+              target="lang/$file.js"
+              if [ ! -f "$source" ]; then
+                  missing_sources+=($source)
+              fi
+              if [ ! -f "$target" ]; then
+                  missing_targets+=($target)
+              fi
           done
-          if [ $status -ne 0 ]; then
-            echo "Lang files do not match expected generated serge files" 1>&2
-            echo "Did you forget to run `npm run lang:build`?" 1>&2
-          else
-            echo "Lang files do match expected generated serge files"
+          if (( ${#missing_sources[@]} )); then
+              echo 'File sets do not match, missing sources ❌'
+              echo '----------------'
+              printf '%s\n' "${missing_sources[@]}"
+              echo '----------------'   
+              match=false
           fi
-          exit $status
+          if (( ${#missing_targets[@]} )); then
+              echo 'File sets do not match, missing targets ❌'
+              echo '----------------'
+              printf '%s\n' "${missing_targets[@]}"
+              echo '----------------'   
+              match=false
+          fi
+          if $match; then
+              echo 'File sets match ✔️'
+          fi
+          echo 'Checking for changes'
+          npm run lang:build 1>/dev/null
+          changes=$(git diff --name-only -- build/)
+          if [ -z "$changes" ]; then
+              echo 'No changes detected ✔️'
+          else
+              echo "Changes detected ❌"
+              echo '----------------'
+              echo "$changes"
+              echo '----------------'
+              echo 'Did you forget to run npm run lang:build?'        
+              match=false
+          fi
+          if $match; then
+              echo 'Lang files good ✔️'
+          else
+              echo 'Lang files not good ❌'
+              exit 1
+          fi
